
@baseUrl = http://localhost:3030/api/v1
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

# @name login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email":"test@test.com",
    "password":"password"
}

###
@token=Bearer {{login.response.body.data.token}}


###
# @name getAllUsers
GET {{baseUrl}}/auth/users
Authorization: {{token}}


# @name changePassword
POST {{baseUrl}}/auth/change-password
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "currentPassword": "passworc",
    "newPassword":"password",
    "confirmNewPassword":"password"
}

###

# @name getAllProducts
GET {{baseUrl}}/products
Authorization: {{token}}

###
# @name saveProducts
POST {{baseUrl}}/products
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "name":"Pen",
    "description":"A very good material for making notes.",
    "price":1.5,
    "image_file": "file"
}

###
# @name getOneProduct
{{baseUrl}}/products/6145d1de38ee7ec2a096e40d
Authorization: {{token}}

###
# @name updateOneProduct
PUT {{baseUrl}}/products/61479b6ab409292ffb88c288
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "name":"Kalipo",
    "description":"This.",
    "price":3.5
}

###
# @name deleteOneProduct
DELETE {{baseUrl}}/products/6145e40537ddad2cfc423949
Authorization: {{token}}

###
# @name addUsers
POST {{baseUrl}}/auth/users 
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "first_name": "Dinah",
    "last_name": "Baah Akuffu",
    "email": "dinah1@test.com",
    "contact_number": "0265654521",
    "password":"newpassword",
    "confirm_password":"newpasswor",
    "role_id":1
}

###
GET http://localhost:4001/api/v1/products