@hostname = localhost
@port = 3030
@contentType = application/json
@apiEndPoint=api/v1
@baseUrl = {{hostname}}:{{port}}/{{apiEndPoint}}
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjEzZDJkYjAzYWRkNjY0NmYwODg5Yjg2IiwiaWF0IjoxNjMxOTY0ODE2LCJleHAiOjE2MzIwNTEyMTZ9.FPM8H2mW7l2OnAAoADoHjWsBBxmAOLLgAuN4jZ5ngv8

GET http://{{baseUrl}}/auth/users
Authorization: {{token}}

###
POST http://{{baseUrl}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email":"test@test.com",
    "password":"password"
}

###
POST http://{{baseUrl}}/auth/change-password
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "currentPassword": "passworc",
    "newPassword":"password",
    "confirmNewPassword":"password"
}

###
GET http://{{baseUrl}}/products
Authorization: {{token}}

###
POST http://{{baseUrl}}/products
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "name":"Kalipo",
    "description":"A nutritious fruit juice.",
    "price":2
}

###
http://{{baseUrl}}/products/6145d1de38ee7ec2a096e40d
Authorization: {{token}}

###
PUT http://{{baseUrl}}/products/6145d1de38ee7ec2a096e40d
Authorization: {{token}}
Content-Type: {{contentType}}

{
    "name":"Kalipo",
    "price":2.5
}

###
GET http://localhost:30410/api/v1/products